FROM alpine:3.19

RUN apk update && apk add --no-cache mariadb mariadb-client bash

COPY conf/mariadb-server.cnf /etc/my.cnf.d/mariadb-server.cnf

COPY tools/init_db.sh /tools/init_db.sh
RUN chmod +x /tools/init_db.sh

EXPOSE 3306

ENTRYPOINT ["/tools/init_db.sh"]
