FROM alpine:3.19

RUN apk update && apk add --no-cache nginx openssl

RUN mkdir -p /run/nginx /etc/nginx/ssl /var/www/html

COPY ./conf/nginx.conf /etc/nginx/nginx.conf

COPY html/ /var/www/html/

COPY tools /tools

RUN chmod +x /tools/generate_ssl.sh && /tools/generate_ssl.sh

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]